### ISSUE TITLE
Redis-Cli hangs after redirecting to other nodes

### ISSUE THREAD

**Issue by talhajansari** [Grokzen/docker-redis-cluster#30] opened 2017-08-22 19:32 UTC
Thanks for the package, @Grokzen.

When I build, run the container and then try accessing using the `redis-cli -c -p 7000` command, everything looks fine. However, when I try and use Redis by either SETing or GETting key, I get the message `Redirected to slot [11058] located at 172.17.0.2:7002` and the redis-cli hangs. It seems like that it's trying to access other redis nodes on 172.17.0.2 (not sure where this IP comes from). 

Do you have any suggestions on how to fix for this?

**Comment by baiwfg2** [comment] 2017-08-24 08:11
I met the same issue. The output is like this:

> root@~$ redis-cli -h 10.110.27.6 -p 7001 -c
> 10.110.27.6:7001> cluster nodes
> dc86c1de4051781d6e38e8cfb858a7b81d1009b1 172.17.0.3:7004 slave e7bf4c63fd9a52b5b43349bfc5a9b73f0d4dff42 0 1503562082948 5 connected
> e7bf4c63fd9a52b5b43349bfc5a9b73f0d4dff42 172.17.0.3:7001 myself,master - 0 0 2 connected 5461-10922
> 3519dba4aeffa8deae450d16282ac2ad54d5500c 172.17.0.3:7000 master - 0 1503562083450 1 connected 0-5460
> 18281a0932633a1226b6516dabf4a11f51b59d85 172.17.0.3:7003 slave 3519dba4aeffa8deae450d16282ac2ad54d5500c 0 1503562084451 4 connected
> 4d147b9f3ca568806046521c4ac6dbf078027ea4 172.17.0.3:7005 slave e5901c4605fb95c71e34fcb85abbe0141f2b7e89 0 1503562083950 6 connected
> e5901c4605fb95c71e34fcb85abbe0141f2b7e89 172.17.0.3:7002 master - 0 1503562084951 3 connected 10923-16383
> 10.110.27.6:7001> set a b
> -> Redirected to slot [15495] located at 172.17.0.3:7002
> Could not connect to Redis at 172.17.0.3:7002: Connection timed out
> Could not connect to Redis at 172.17.0.3:7002: No route to host

How to handle this situation ? Please help. Thanks

**Comment by baiwfg2** [comment] 2017-08-24 08:57
Ah, I found it. @talhajansari  Do not use `-p` option. Use `--net=host` to launch. You can refer to [https://redis.io/topics/cluster-tutorial#redis-cluster-and-docker](https://redis.io/topics/cluster-tutorial#redis-cluster-and-docker) and [https://docs.docker.com/engine/userguide/networking/#exposing-and-publishing-ports](https://docs.docker.com/engine/userguide/networking/#exposing-and-publishing-ports)

**Comment by Grokzen** [comment] 2017-12-03 11:54
@talhajansari Closing this one as fixed because the problem is on your end and not inside the docker container itself.

**Closed by Grokzen** 2017-12-03 11:54 UTC
